### ISSUE TITLE
pip install -U lightautoml[nlp] does not work

### ISSUE THREAD

**Issue by numomcmc** [sb-ai-lab/LightAutoML#146]
### To Reproduce
The installation instruction as describe [here](https://github.com/sb-ai-lab/LightAutoML) contains errors.

1. in linux or Conda Powershell or Jupyter notebook on Kaggle
1. Run 'pip install -U lightautoml[nlp]' or !pip install -U lightautoml[nlp] in Kaggle notebook
3. Get EM:  [nlp]...  Not valid.  The same applies to [cv] and [report]

only [all] works.  Please revise your documentation.  

Best,
S

### Checklist
- [ ] bug description
- [ ] steps to reproduce
- [ ] expected behavior
- [ ] code sample / screenshots

**Comment by alexmryzhkov** [comment]
Hi @numomcmc,

I have reproduced your issue - everything works fine. Proof screenshot:
<img width="1194" alt="Снимок экрана 2024-01-23 в 15 28 34" src="https://github.com/sb-ai-lab/LightAutoML/assets/14252406/0d800870-3415-4952-a79e-fd4325a9fd8f">

**Comment by numomcmc** [comment]
Hi Alexander

When you said "everything works fine", what does that mean?  Which version
of LAMA were you installing and what version of Python and Pandas, and
Numpy?  Please clarify.

Thank you.
S

**Comment by alexmryzhkov** [comment]
@numomcmc you said that you get the message `[nlp] is not valid` but I have shown that it's not the case - that's why I said "everything works fine"

From the end of the `!pip install -U lightautoml[nlp]` command output I have received several minutes ago the line below:

`Successfully installed StrEnum-0.4.15 alabaster-0.7.16 autowoe-1.3.2 cmaes-0.10.0 imagesize-1.4.1 joblib-1.2.0 json2html-1.3.0 lightautoml-0.3.8.1 lightgbm-3.2.1 pandas-1.5.3 poetry-core-1.8.1 sphinx-7.2.6 sphinxcontrib-applehelp-1.0.8 sphinxcontrib-devhelp-1.0.6 sphinxcontrib-htmlhelp-2.0.5 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.7 sphinxcontrib-serializinghtml-1.1.10`
